#!/bin/bash

DIR=$1
MAXKB=$2

keepDelete="true"

while [[ keepDelete -eq "true" ]]; do

    totalFiles=`ls -ltr $DIR | grep ^- | wc -l | sed 's/ //g'`

    if [[ $totalFiles -eq 0 ]]; then
        echo "There are no files to delete"
        exit 0

    elif [[ $totalFiles -eq 1 ]]; then
        echo "Can't delete no more files. There is only 1 file."
        exit 0
    fi

    duDir=`du -sk $DIR 2>/dev/null`;
    dirSize=`echo $duDir | sed 's/\(.*\) .*/\1/'`;

    if [[ $dirSize -gt $MAXKB ]]; then
        fileToDelete=`ls -ltr $DIR | grep ^- | head -n 1 | sed 's/.* \(.*\)$/\1/'`
        echo "Going to delete file $DIR/$fileToDelete"
        rm -f $DIR/$fileToDelete
    else
        echo "Directory $DIR now has $dirSize kb"
        exit 0
    fi

done
