#!/bin/bash

# Usage: hm config <key>=<value>
# Summary: Set variables to be used in other scripts
# Help: Set any script variable with this script.o
#  
#  
#  Ex: hm config <key>=<value> <key2>=<value2>
#   
# Provide hm completions

OPTIONS=("pt.vpn-username" "pt.vpn-password")

CONFIG_FILE="$HOME/.hmconfig"

while test $# -gt 0; do
    case "$1" in 
        --complete) 
            for option in ${OPTIONS[*]}
            do
                printf "%s\n" $option
            done
            exit 0
            ;;
        h)
            hm help config
            exit 0
            ;;
        *) 
            OPTION=$(echo $1 | sed -e 's/\(.*\)=.*/\1/g')
            VALUE=$(echo $1 | sed -e 's/.*=\(.*\)/\1/g')

            if [ ! -f $CONFIG_FILE ]; then
                touch $CONFIG_FILE 
            fi

            if grep -q "$OPTION *= " $CONFIG_FILE; then   
                sed -i "" "s/\($OPTION *= *\).*/\1$VALUE/" $CONFIG_FILE
            else
                echo "$OPTION = $VALUE" >> $CONFIG_FILE
            fi

            shift
            ;;
    esac
done

