#!/bin/sh

POST_BODY="introtxt=Please+register+yourself+using+a+%3Cb%3Evalid+e-mail+address%3C%2Fb%3E%0D%0A+++++++++++++++++++++to+allow+us+to+send+you+an+evaluation+license.&backurl=%2Fproducts%2Fdbvis%2Feval%2F&homeurl=index.jsp&downloadurl=%2Fform%2Feval-process.jsp&prodid=72&prodLabel=DbVisualizer&prodVersion=8.0.4&email=hugo.m.marcelino%40gmail.com&lastname="

curl -H "Content-Type:application/x-www-form-urlencoded" -H "Content-Length:343" -d $POST_BODY http://www.dbvis.com/form/eval-process.jsp

osascript <<eof
	tell application "Mail"
	
		set notfound to true
		set counter to 1
		
		set myaccount to account "Gmail"
		repeat while notfound = true and counter ≤ 5
			
			check for new mail for myaccount
			
			tell account "Gmail"
				set messageList to every message of mailbox "INBOX"
				repeat with aMessage in messageList
					set theSubject to subject of aMessage
					if theSubject contains "DBVisualizer" and theSubject contains "Evaluation Licens" then
						set rawMessage to source of aMessage & return
						set outputFile to open for access file "fast:tmp:dbvis-license-mail.txt" with write permission
						write rawMessage to outputFile
						close access outputFile
						set notfound to false
						exit repeat
					end if
				end repeat
				set counter to counter + 1
				delay 2
			end tell
		end repeat
	end tell
eof

sed -e '/^[^dbvis\.license\.]/d' /tmp/dbvis-license-mail.txt | sed -e '/^ *$/d' | sed -e '/^support@dbvis.com*$/d' > ~/.dbvis/dbvis.license
