#!/bin/bash

# Usage: hm iterm -t <tab-name> [-p <profile-name>]
# Summary: Renames the current tab and set a new profile.
# Help: Renames the current and set a new profile.
#
#  * A iterm2 console tab with the name sigrecpe1 and the profile prod
#    $> hm iterm -t sigrecpe1 -p prod

TAB_NAME="none"
PROFILE_NAME="default";

while getopts "t:p:h" optname
do
    case "$optname" in
        "t")
            TAB_NAME="$OPTARG"
            ;;
        "p")
            PROFILE_NAME="$OPTARG"
            ;;
        "h")
            hm help iterm
            exit 0
            ;;
        "*")
            echo "Illegal option"
            exit 1
            ;;
    esac
done

if [ $TAB_NAME = "none" ] || [ $TAB_NAME = "" ]; then
  hm help iterm
  exit 1
fi

TAB_NAME=`echo $TAB_NAME | tr [a-z] [A-Z]` > /dev/null

# change the tab title
echo -e "\033];$TAB_NAME\007"

# change the profile
echo -e "\033]50;SetProfile=$PROFILE_NAME\a"

# done
exit 0;
