#!/usr/bin/env ruby

# Usage: hm rgit <command>
# Summary: Execute a git command on all the sub directories
# Help: For each directory execute the git command
#
#  * Examples:
# 
#     hm rgit fetch
#     hm rgit pull --rebase

args = ARGV.join(" ")

Dir.foreach('.') do |f|
    next unless File.directory? f #only dirs
    next if f =~ /\.+/  #skip . and ..

    Dir.chdir(f) do |dir|
        if Dir.new('.').include?('.git')

            output = `git #{args} 2>&1`

            unless output.empty? && $?.success?
                puts dir
                puts "-"*dir.size
                puts output
                puts "\n"
            end
        end

    end
end
