#!/bin/bash

# Usage: hm setenv -n <env-name> 
# Summary: Set the environment as requested
# Help: Set the environment as requested
#
#  opts:
#    -n: the env name. [Default: huma]
#    -h: print help information
#
#  * Set the environment for inspire
#    $> hm setenv -n ingg

env="huma"

while getopts "n:" optname
do
    case "$optname" in
        "n")
            env="$OPTARG"
            ;;
        "h")
            hm help setenv
            exit 0
            ;;
        "?")
            echo "Unknown option $OPTARG"
            ;;
        ":")
            echo "No argument value for option $OPTARG"
            ;;
         *)
            # Should not occur
            echo "Unknown error while processing options"
         ;;
    esac
done

maven_dir=~/projects/engines/maven

# Delete old symlink before setting a new one
if [ -e $maven_dir ]; then
    rm ~/projects/engines/maven
fi

if [[ $env == "huma" ]]; then
    maven_home=~/projects/engines/apache-maven-3.2.3
    echo "Using maven: $maven_home"
    ln -s $maven_home $maven_dir

elif [[ $env == "ingg" ]]; then 
    maven_home=~/projects/company/enear/inspire/engines/apache-maven-3.2.3
    echo "Using maven: $maven_home"
    ln -s $maven_home $maven_dir

else
    echo "Unsupported env name: $env"
    exit 1
fi

# done
exit 0;
