#!/bin/bash

alias ls='ls -G'
alias ll='ls -lGha'
alias vi='vim'

alias mvnd='mvn -Xnoagent -Djava.compiler=NONE -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8999'
alias mci='mvn clean install'
alias mcim='mvn clean install -pl'

alias pt='cd ~/projects/company/pt'
alias wd='cd ~/projects/company/cob/'
alias ee='cd ~/projects/company/equalexperts/'

alias go-prod="hm iterm -p production"
alias go-dev="hm iterm -p development"

alias http_serve="python -m SimpleHTTPServer"

# alias imvn="mvn -s /Users/hugomarcelino/projects/company/enear/inspire/confs/maven-settings.xml "
alias setJdk6='export JAVA_HOME=$(/usr/libexec/java_home -v 1.6)'
alias setJdk7='export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)'
alias setJdk8='export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)'
alias setJdk9='export JAVA_HOME=$(/usr/libexec/java_home -v 9)'
alias setJdk10='export JAVA_HOME=$(/usr/libexec/java_home -v 10)'
alias setJdk11='export JAVA_HOME=$(/usr/libexec/java_home -v 11)'

alias du="ncdu --color dark -rr -x --exclude .git --exclude node_modules"
alias top='htop'
alias cat='bat'
