INSTALLER_DIR="$HOME/dotfiles/cmdline";

export HISTCONTROL=erasedups
export HISTSIZE=10000
shopt -s histappend

source $INSTALLER_DIR/export
source $INSTALLER_DIR/aliases
 
export PATH=/opt/local/bin:/opt/local/sbin:/usr/local/sbin:$PATH
export MANPATH=/opt/local/share/man:$MANPATH
 
source $INSTALLER_DIR/completion
 
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
source $(brew --prefix autoenv)/activate.sh

source $INSTALLER_DIR/prompt

eval "$(/Users/hugomarcelino/projects/company/spotqa/vts-cli/bin/vcli init -)"
eval "$(/Users/hugomarcelino/projects/company/temp/sub/bin/tt init -)"
